routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\DigitalController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('users', UserController::class);
    Route::resource('digitais', DigitalController::class);
});

app/Models/Digital.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Digital extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'cpf',
        'nome',
        'dt_nascimento',
        'tipo_rede_social',
        'usuario',
        'seguidores',
        'foto'
    ];
}

app/Http/Controllers/DigitalController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Digital;
use Auth;
use GuzzleHttp\Client;

class DigitalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $data = Digital::orderBy('id','DESC')->paginate(5);
        return view('digital.index',compact('data'))
            ->with('i', ($request->input('page', 1) - 1) * 5);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('digital.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'cpf' => 'required|unique:digitals,cpf',
            'nome' => 'required',
            'dt_nascimento' => 'required',
            'tipo_rede_social' => 'required',
            'usuario' => 'required',
        ]);

        $input = $request->all();

        if ($input->tipo_rede_social == 'instagram') {
            $curl = curl_init();
            curl_setopt_array($curl, [
            CURLOPT_URL => "https://www.instagram.com/{$input->usuario}/channel/?__a=1",
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => "",
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 30,
            CURLOPT_USERAGENT => "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36",
            CURLOPT_SSL_VERIFYPEER => false,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => "GET",
            CURLOPT_POSTFIELDS => ""
            ]);

            $response = curl_exec($curl);
            $err = curl_error($curl);
            curl_close($curl);
            if ($err) {
                return redirect()->route('digitais.index')->with('success',"cURL Error #:" . $err);
            } else {
                $data = json_decode( $response, true );
                $foto_url = $data['graphql']['user']['profile_pic_url_hd'];
                $seguidores = $data['graphql']['user']['edge_followed_by']['count'];
                $input['foto'] = $foto_url;
                $input['seguidores'] = $seguidores;
            }
        }

        $digital = Digital::create($input);

        return redirect()->route('digitais.index')->with('success','Digital criado com sucesso');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Digital  $digital
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $digital = Digital::find($id);
        return view('digital.show',compact('digital'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Digital  $digital
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $digital = Digital::find($id);
        return view('digital.edit',compact('digital'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\Request  $request
     * @param  \App\Models\Digital  $digital
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'cpf' => 'required|unique:digitals,cpf,'.$id,
            'nome' => 'required',
            'dt_nascimento' => 'required',
            'tipo_rede_social' => 'required',
            'usuario' => 'required',
        ]);

        $input = $request->all();

        if ($input['tipo_rede_social'] == 'instagram') {
            $curl = curl_init();
            curl_setopt_array($curl, [
            CURLOPT_URL => "https://www.instagram.com/{$input['usuario']}/channel/?__a=1",
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => "",
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 30,
            CURLOPT_USERAGENT => "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36",
            CURLOPT_SSL_VERIFYPEER => false,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => "GET",
            CURLOPT_POSTFIELDS => ""
            ]);

            $response = curl_exec($curl);
            $err = curl_error($curl);

            curl_close($curl);

            if ($err) {
                return redirect()->route('digitais.index')->with('danger',"cURL Error #:" . $err);
            } else {
                $data = json_decode( $response, true );
                if ($data == null) {
                    return redirect()->route('digitais.index')->with('danger',"Erro obtendo dados, tente novamente mais tarde.");
                }else{
                    $foto_url = $data['graphql']['user']['profile_pic_url_hd'];
                    $seguidores = $data['graphql']['user']['edge_followed_by']['count'];
                    $input['foto'] = $foto_url;
                    $input['seguidores'] = $seguidores;
                }
            }

        }

        $digital = Digital::find($id);
        $digital->update($input);

        return redirect()->route('digitais.index')->with('success','Digital atualizado com sucesso');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Digital  $digital
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Digital::find($id)->delete();
        return redirect()->route('digitais.index')->with('success','Digital excluído com sucesso');
    }
}

resources/views/digital/create.blade.php
@extends('layouts.app')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Criar novo digital</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('digitais.index') }}"> Voltar</a>
        </div>
    </div>
</div>


@if (count($errors) > 0)
  <div class="alert alert-danger">
    <strong>Opa!</strong> Houve alguns problemas com sua entrada.<br><br>
    <ul>
       @foreach ($errors->all() as $error)
         <li>{{ $error }}</li>
       @endforeach
    </ul>
  </div>
@endif



{!! Form::open(array('route' => 'digitais.store','method'=>'POST')) !!}
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>CPF:</strong>
            {!! Form::text('cpf', null, array('placeholder' => '000.000.000-00','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Nome:</strong>
            {!! Form::text('nome', null, array('placeholder' => 'Seu nome','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Data de Nascimento:</strong>
            {!! Form::date('dt_nascimento', null, array('class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Tipo Rede Social:</strong>
            {!! Form::select('tipo_rede_social', ['instagram' => 'Instagram', 'facebook' => 'Facebook', 'tiktok' => 'TikTok', 'twitter' => 'Twitter'], null, ['placeholder' => 'Rede Social...', 'class' => 'form-control']) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Usuário:</strong>
            {!! Form::text('usuario', null, array('placeholder' => 'Seu nome','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Salvar</button>
    </div>
</div>
{!! Form::close() !!}
@endsection

resources/views/digital/edit.blade.php
@extends('layouts.app')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Editar digital</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('digitais.index') }}"> Voltar</a>
        </div>
    </div>
</div>


@if (count($errors) > 0)
  <div class="alert alert-danger">
    <strong>Opa!</strong> Houve alguns problemas com sua entrada.<br><br>
    <ul>
       @foreach ($errors->all() as $error)
         <li>{{ $error }}</li>
       @endforeach
    </ul>
  </div>
@endif


{!! Form::model($digital, ['method' => 'PATCH','route' => ['digitais.update', $digital->id]]) !!}
<div class="row">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>CPF:</strong>
                {!! Form::text('cpf', null, array('placeholder' => '000.000.000-00','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nome:</strong>
                {!! Form::text('nome', null, array('placeholder' => 'Seu nome','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Data de Nascimento:</strong>
                {!! Form::date('dt_nascimento', null, array('class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Tipo Rede Social:</strong>
                {!! Form::select('tipo_rede_social', ['instagram' => 'Instagram', 'facebook' => 'Facebook', 'tiktok' => 'TikTok', 'twitter' => 'Twitter'], null, ['placeholder' => 'Rede Social...', 'class' => 'form-control']) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Usuário:</strong>
                {!! Form::text('usuario', null, array('placeholder' => 'Seu nome','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Atualizar</button>
        </div>
    </div>
</div>
{!! Form::close() !!}

@endsection

resources/views/digital/index.blade.php
@extends('layouts.app')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Gerenciamento Digital</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('digitais.create') }}"> Criar novo digital</a>
        </div>
    </div>
</div>


@if ($message = Session::get('success'))
<div class="alert alert-success">
  <p>{{ $message }}</p>
</div>
@endif

@if ($message = Session::get('danger'))
<div class="alert alert-danger">
  <p>{{ $message }}</p>
</div>
@endif


<table class="table table-bordered">
 <tr>
   <th>No</th>
   <th>CPF</th>
   <th>Nome</th>
   <th>Data de Nascimento</th>
   <th>Tipo de Rede Social</th>
   <th>Perfil</th>
   <th>Seguidores</th>
   <th>URL</th>
   <th width="280px">Ação</th>
 </tr>
 @foreach ($data as $key => $digital)
  <tr>
    <td>{{ ++$i }}</td>
    <td>{{ $digital->cpf }}</td>
    <td>{{ $digital->nome }}</td>
    <td>{{ \Carbon\Carbon::parse($digital->dt_nascimento)->format('d/m/Y') }}</td>
    <td>{{ $digital->tipo_rede_social }}</td>
    <td><img src="{{ $digital->foto }}"></td>
    <td>{{ $digital->seguidores }}</td>
    <td><a href="https://www.{{$digital->tipo_rede_social}}.com/{{ $digital->usuario }}">Link</a></td>
    <td>
       <a class="btn btn-info" href="{{ route('digitais.show',$digital->id) }}">Mostrar</a>
       <a class="btn btn-primary" href="{{ route('digitais.edit',$digital->id) }}">Editar</a>
       {!! Form::open(['method' => 'DELETE','route' => ['digitais.destroy', $digital->id],'style'=>'display:inline']) !!}
           {!! Form::submit('Deletar', ['class' => 'btn btn-danger']) !!}
       {!! Form::close() !!}
    </td>
  </tr>
 @endforeach
</table>

{!! $data->withQueryString()->links('pagination::bootstrap-5') !!}

@endsection

resources/views/digital/show.blade.php
@extends('layouts.app')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Mostrar usuário</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('digitais.index') }}"> Voltar</a>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>CPF:</strong>
                {{ $digital->cpf }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nome:</strong>
                {{ $digital->nome }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Data de Nascimento:</strong>
                {{ \Carbon\Carbon::parse($digital->dt_nascimento)->format('d/m/Y') }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Tipo Rede Social:</strong>
                {{ $digital->tipo_rede_social }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Usuário(a):</strong>
                {{ $digital->users->login }}
            </div>
        </div>
    </div>
@endsection